/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.marketchapin.frontEnd.Admin;

import com.mycompany.marketchapin.Conexiones.CAdmin;
import com.mycompany.marketchapin.controladores.CambioFrame;
import com.mycompany.marketchapin.frontEnd.Frame;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class topSucursal extends javax.swing.JPanel {

    /**
     * Creates new form topSucursal
     */
    private Frame principal;
    private Reportes anterior;

    public topSucursal(Frame principal, Reportes anterior) {
        this.principal = principal;
        this.anterior = anterior;
        initComponents();
        agregarTablaa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Top ingresos de sucursales");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Top", "Nombre", "Ingresos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CambioFrame nuevo = new CambioFrame(principal, anterior);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void agregarTablaa() {
        CAdmin cAdmin = new CAdmin();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        // Obtener el top 3 de sucursales con más ingresos
        Map<String, Double> topSucursales = cAdmin.obtenerTop3SucursalesConIngresos();

        // Imprimir el top 3
        int i = 1;
        System.out.println("Top 3 de sucursales con más ingresos:");
        for (Map.Entry<String, Double> entry : topSucursales.entrySet()) {
            String nombreSucursal = entry.getKey();
            double ingresos = entry.getValue();
            System.out.println(nombreSucursal + ": " + ingresos + " ingresos");
            String [] entrada = {i+"",nombreSucursal,ingresos+""};
            modelo.addRow(entrada);
        }

        // Cerrar la conexión
        cAdmin.cerrarC();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
